import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Marquee from "@/components/home/Marquee";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";

const notoSerifBangla = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBangla.className} h-full antialiased`}
    >
      <body className=" min-h-full flex flex-col ">
        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            style: {
              background: "#18181b",
              color: "#fff",
            },
          }}
        />
        <Navbar marquee={<Marquee />} />

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
